import * as React from "react";
import * as Types from "./types";

declare function HomePage(props: {
  as?: React.ElementType;
  videoHeaderBack?: Types.Devlink.Slot;
  componentLang?: Types.Devlink.Slot;
  componentTheme?: Types.Devlink.Slot;
  componentGoogleMap?: Types.Devlink.Slot;
  menuHome?: React.ReactNode;
  menuServices?: React.ReactNode;
  menuPartners?: React.ReactNode;
  menuContact?: React.ReactNode;
  titleHome?: React.ReactNode;
  subtitleHome?: React.ReactNode;
  devicesHome?: React.ReactNode;
  downloadHome?: React.ReactNode;
  dogsitterTitle?: React.ReactNode;
  dogsitterText?: React.ReactNode;
  dogbabyTitle?: React.ReactNode;
  dogbabyText?: React.ReactNode;
  dogtrainerTitle?: React.ReactNode;
  dogtrainerText?: React.ReactNode;
  vetTitle?: React.ReactNode;
  vetText?: React.ReactNode;
  nurseTitle?: React.ReactNode;
  nurseText?: React.ReactNode;
  activityTitle?: React.ReactNode;
  menuFastLinks?: React.ReactNode;
  menuSocials?: React.ReactNode;
  activityText?: React.ReactNode;
  servicesTitle?: React.ReactNode;
  servicesSubtitle?: React.ReactNode;
  leitmotiv?: React.ReactNode;
  menuLegacy?: React.ReactNode;
  menuPrivacy?: React.ReactNode;
  menuTerms?: React.ReactNode;
  copyright?: React.ReactNode;
  promo?: React.ReactNode;
  moreQuestions?: React.ReactNode;
  menuNavigation?: React.ReactNode;
}): React.JSX.Element;
